# Generated by Django 5.1.14 on 2025-11-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_genre_genre_name_case_insensitive_unique_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["authorname"]},
        ),
        migrations.RenameField(
            model_name="author",
            old_name="first_name",
            new_name="authorname",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_name",
        ),
    ]
