# Generated by Django 5.1.14 on 2025-11-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "文章分类", "verbose_name_plural": "文章分类"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "标签", "verbose_name_plural": "标签"},
        ),
    ]
